[general]
fail_mode={{ OPNsense.AppId.general.failmode|default('closed') }}
classify_packets={{ OPNsense.AppId.general.classify_packets|default('16') }}
divert_port_base=8100
pidfile=/var/run/appidd.pid
policy=/usr/local/etc/appidd/policy.json
database=/var/db/appid/active.json
protocols=/usr/local/etc/appidd/protos.txt
custom_applications=/usr/local/etc/appidd/custom_applications.conf

[update]
url={{ OPNsense.AppId.general.update_url|default('') }}
