###################################################################
# Local syslog-ng configuration filter definition [appidd].
###################################################################
filter f_local_appidd {
    program("appidd");
};
