[start_watchdog]
command:/usr/sbin/daemon -f -r -P /var/run/commit_watchdog_sup.pid -p /var/run/commit_watchdog.pid /usr/local/bin/python3 /usr/local/opnsense/scripts/system/commit_watchdog.py
parameters:
type:script
message:start supervised detached commit session watchdog daemon

[check_watchdog]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/system/commit_watchdog.py --check
parameters:
type:script
message:check commit session watchdog daemon supervisor

[reload_all]
command:/usr/local/etc/rc.reload_all
parameters:
type:script
message:reload all services
