[start_watchdog]
command:/usr/sbin/daemon -f -p /var/run/commit_watchdog.pid /usr/local/bin/python3 /usr/local/opnsense/scripts/system/commit_watchdog.py
parameters:
type:script
message:start detached commit session watchdog daemon

[reload_all]
command:/usr/local/etc/rc.reload_all
parameters:
type:script
message:reload all services
