[stop]
command:/usr/local/etc/rc.d/appidd stop
parameters:
type:script
message:stop application control daemon
allowed_groups:wheel,wwwonly

[start]
command:/usr/local/etc/rc.d/appidd start
parameters:
type:script
message:start application control daemon

[restart]
command:/usr/local/etc/rc.d/appidd restart
parameters:
type:script
message:restart application control daemon
description:Restart application control daemon

[reload]
command:/usr/local/opnsense/scripts/appid/generate_policy.php && /usr/local/etc/rc.d/appidd reload
parameters:
type:script
message:reload application control policy

[status]
command:/usr/local/sbin/pluginctl -s appidd status
parameters:
errors:no
type:script_output
message:get application control daemon status

[update]
command:/usr/local/opnsense/scripts/appid/update_db.py
parameters:
type:script_output
message:update application control database
description:Update application control database

[list.applications]
command:/usr/local/opnsense/scripts/appid/list_applications.py
parameters:
type:script_output
message:list application control applications

[list.categories]
command:/usr/local/opnsense/scripts/appid/list_applications.py --categories
parameters:
type:script_output
message:list application control categories

[list.details]
command:/usr/local/opnsense/scripts/appid/list_applications.py --details
parameters:
type:script_output
message:list application control applications including properties

[database.info]
command:/usr/local/opnsense/scripts/appid/list_applications.py --info
parameters:
type:script_output
message:show application control database information
